# Generated by Django 4.1.5 on 2023-01-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('car_type', models.CharField(choices=[('SMALL_CAR', 'sm'), ('MINI_VAN', 'mv'), ('SUV', 'suv')], max_length=10)),
                ('car_model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'p'), ('DISEL', 'd'), ('ELECTRIC', 'ev')], max_length=20)),
                ('car_image', models.ImageField(upload_to='')),
                ('price_per_hour', models.IntegerField()),
                ('is_available', models.BooleanField()),
                ('number_of_seats', models.CharField(max_length=2)),
                ('transmission', models.BooleanField(max_length=20)),
                ('milage', models.FloatField(max_length=20)),
                ('air_bag', models.BooleanField()),
                ('location', models.CharField(max_length=100)),
                ('free_cancellation', models.BooleanField()),
                ('driver_aged', models.BooleanField()),
            ],
        ),
    ]
